[features]
seeds = true

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[programs.localnet]
disco = "EJQnbXhsLS92wsAXg1vPaZt88hfzmuhcqBVLQBn9h23x"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/danmt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
